development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: falon
  password: myflix

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: falon
  password: myflix
